# Configuration for the typos spell checker utility (<https://github.com/crate-ci/typos>).

[files]
extend-exclude = [
]

[default]
extend-ignore-identifiers-re = [
]

[default.extend-words]


[default.extend-identifiers]
# We sometimes use "typ" as "type" is a reserved keyword
typ = "typ"

